# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "CentOS7"

  config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"

  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "master"
    master.vm.provider "hyperv" do |v|
      v.vmname = "master"
      v.memory = "2048"
    end
    master.vm.provision "shell", inline: <<-SHELL
      echo "IPADDR1=\"192.168.100.100\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0
      systemctl restart network
    SHELL
  end

  (1..3).each do |i|
    config.vm.define "slave0#{i}" do |slave|
      slave.vm.hostname = "slave0#{i}"
      slave.vm.provider "hyperv" do |v|
        v.vmname = "slave0#{i}"
#        v.memory = "768"
      end
      slave.vm.provision "shell", inline: <<-SHELL
        echo "IPADDR1=\"192.168.100.10#{i}\"" >> /etc/sysconfig/network-scripts/ifcfg-eth0
        systemctl restart network
      SHELL
    end
  end

  config.vm.provision "shell", path: "https://raw.githubusercontent.com/dalton-lee/bigdata-explore/master/Vagrant/provisioner.sh"

end
